#!/bin/bash

##script to detect multiple keyboards at login and launch fbxkb if found.

# start fbxkb if multiples present. 

#check multiple keyboard layouts
if  setxkbmap -query | grep -sq '^layout:.*,'; then
	echo "multiple keyboards found"
	fbxkb &
	exit 0
else
	echo "only one keyboard"
fi

exit 0
